In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset=pd.read_csv('/Data.csv')
x=dataset.iloc[ : , :-1].values
y=dataset.iloc[ : , -1].values

print(x)
print(y)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]
['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer

imputer=SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3]=imputer.transform(x[:,1:3])

print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoding',OneHotEncoder(),[0])],remainder='passthrough')
x= np.array(ct.fit_transform(x))



In [41]:
print(x)

[[0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0
  63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0
  38.77777777777778 52000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [24]:
from sklearn.preprocessing import LabelEncoder

le=LabelEncoder()
y=le.fit_transform(y)

print(y)

[0 1 0 0 1 1 0 1 0 1]


In [26]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=1)

In [43]:
print(x_train)

[[1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 35.0 58000.0]]


In [44]:
print(x_test)


[[1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


In [29]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [30]:
print(y_test)

[0 1]


In [52]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

x_train[:,10:]=ss.fit_transform(x_train[:,10:])
x_test[:,10:]=ss.transform(x_test[:,10:])

print(x_train)
print(x_test)

[[1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 -0.1915918438457855
  -1.0781259408412427]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 -0.014117293757057819
  -0.07013167641635418]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.5667085065333239
  0.6335624327104546]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 -0.30453019390224867
  -0.307866172742979]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 -1.901801144700799
  -1.4204636155515822]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.1475343068237056
  1.2326533634535488]
 [1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.4379472069688966
  1.5749910381638883]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 -0.7401495441200352
  -0.5646194287757336]]
[[1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 -1.0 -1.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 1.0]]
